---
- name: check URL response of tomcat
  uri:
    url: "{{item.a}}"
    status_code: "{{item.b}}"
  with_items:
    - {a: "{{m}}", b: "{{n}}"} 
    - {a: "{{o}}", b: "{{n}}"} 
    - {a: "{{p}}", b: "{{n}}"} 

...
