---
- name: check file file1 is exucuted and if so delete it 
  hosts: all
  tasks:
   - name: check if file1 is executable
     stat:
       path: /tmp/file1
     register: a
   - name: Display output of above module
     debug:
       var: a
   - name: create directory of name file1
     file:
       name: /tmp/file1
       state: absent
     when: a.stat.executable == true    
...
