---
- name: implement when condition
  hosts: all
  vars:
   - a: 10
  tasks: 
   - name: install tree
     apt:
       name: tree
       state: present
       update_cache: no
     when: a==10
    
...
