---
- name: Create users and files/directories in user home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create Files or directory in the user home dir
      file:
        name: "{{d}}"
        state: "{{e}}"
...
