---
- name: check the status of apache URL
  uri:
   url: "{{item}}"
   status_code: 200
  with_items:
      - http://172.31.88.196
      - http://172.31.86.40
      - http://172.31.15.104
      - http://172.31.8.185
...
